#!/usr/bin/env python

__doc__ = """
Hrpsys_Dashboard
GUI for the hrpsys robots."""

import roslib
roslib.load_manifest('hrpsys_ros_bridge')

from hrpsys_ros_bridge.hrpsys_dashboard import *

WXVER = '2.8'
import wxversion
if wxversion.checkInstalled(WXVER):
  wxversion.select(WXVER)
else:
  print >> sys.stderr, "This application requires wxPython version %s"%(WXVER)
  sys.exit(1)

import wx

if __name__ == '__main__':
  app = wx.App()
  frame = HrpsysFrame(None)
  frame.Show()
  app.MainLoop()

