#!/usr/bin/env python

import sys

import roslib
pkg = 'hrpsys_ros_bridge'

import imp
try:
    imp.find_module(pkg)
except:
    roslib.load_manifest(pkg)

from rqt_gui.main import Main

import hrpsys_ros_bridge
import hrpsys_ros_bridge.hrpsys_dashboard

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg))
