#!/usr/bin/python

cosnames = "omniNames"
port_number = 15005

import rtmstart
import roslaunch

p = rtmstart.start_cosname(cosnames, port_number)

try:
    roslaunch.main()
finally:
    # if omniName is invoked from this script, stop this
    if p :
        print "\033[34m[rtmlaunch] terminate", cosnames, "at port", port_number, "\033[0m"
        p.terminate()

