#!/bin/bash

if [ "`lsb_release -cs`" = "lucid" -a "`grep ^::1 /etc/hosts`" ]; then
    echo -e "\e[1;31mYou must comment out \\"::1  localhost\\" line from /etc/hosts\e[m"
    exit 1
fi
if [ "`pgrep omniNames -u 0`" ]; then
    gksu /etc/init.d/omniorb4-nameserver stop
    if [ $? != 0 ]; then
	echo -e "\e[1;31mrunning omniNames invoked by root\e[m" 1>&2
	echo -e "\e[1;31mtry \`sudo /etc/init.d/omniorb4-nameserver stop\`\e[m" 1>&2
	exit 1;
    fi
fi

port=2809
while getopts p: OPT
do
    case $OPT in
	"p") port=${OPTARG}; shift 2;;
    esac
done

cosnames="/usr/bin/omniNames"
orb="omniORB"
hostname=`hostname`
currdir=`pwd`
pname=`basename $cosnames`

do_stop(){
    netstat_tanp=`netstat -tanp`
    _netstat=`netstat -tanp 2> /dev/null | grep $port | awk '{if($7!="-"){print $7;}}'`
    echo "A possible process that is using $port port:" $_netstat
    if test "x$_netstat" = "x"; then
	echo "No process using port number ${_port} on the system."
	return 1
    fi
    if test "x$_netstat" = "x"; then
	echo "Process information could not be identified."
	return 1
    fi

    _pid=`echo $_netstat | awk 'BEGIN{FS="/";}{print $1;}'`
    pname_of_nsport=`echo $_netstat | awk 'BEGIN{FS="/";}{print $2;}'`
    pid_of_nsport=$_pid
    echo "$_port port is used by $pname_of_nsport (pid = $_pid)."
    echo "$pname (pid: $pid_of_nsport) is running"
    pkill -f $pname
    echo "$pname (pid: $pid_of_nsport) are killed"
}

do_start()
{
    echo 'Starting omniORB omniNames: '$hostname':'$port
    rm -f ./omninames-$hostname.log
    rm -f ./omninames-$hostname.bak
    $cosnames -start $port -logdir $currdir
}

case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart | *)
	do_stop
	do_start
	;;
esac

exit 0


