#!/bin/bash

if [ "`lsb_release -cs`" = "lucid" -a "`grep ^::1 /etc/hosts`" ]; then
    echo -e "\e[1;31mYou must comment out \\"::1  localhost\\" line from /etc/hosts\e[m"
    exit 1
fi
if [ "`pgrep omniNames -u 0`" ]; then
    gksu /etc/init.d/omniorb4-nameserver stop
    if [ $? != 0 ]; then
	echo -e "\e[1;31mrunning omniNames invoked by root\e[m" 1>&2
	echo -e "\e[1;31mtry \`sudo /etc/init.d/omniorb4-nameserver stop\`\e[m" 1>&2
	exit 1;
    fi
fi

##
GETOPT=`getopt -o o: -l output:,text,ctx:,gtest_output: -- "$@"` ; [ $? != 0 ] && usage_exit
eval set -- "$GETOPT"
while true
do
  case $1 in
  --gtest_output)  OUTFILE=$2      ; shift 2 ;;
  *)   shift ; break ;;
  esac
done

OUTFILE=${OUTFILE/xml:/}
if [ "${OUTFILE}" ]; then
    cat<<EOF > ${OUTFILE}
<testsuite errors="0" failures="0" name="unittest.suite.TestSuite" tests="1" time="0.0">
  <testcase classname="__main__.TestGlcEncode" name="test_glc_encode" time="0.0"></testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
EOF
fi

do_stop(){
    echo -n "Kill omniNames " 1>&2 ; pgrep omniNames -lx 1>&2; echo "" 1>&2
    pkill -KILL omniNames
}

do_start()
{
    `rospack find openrtm`/bin/rtm-naming
    sleep 1 # wait to omniNaming start up
    tail ./omninames-`hostname`.log
}

case "$1" in
    start)
	do_start
	;;
    stop)
	do_stop
	;;
    restart | *)
	do_stop
	do_start
	;;
esac

exit 0


