#include <BasicDataType.idl>

module RTC
{
    const octet CMD_GO_ACTUAL = 0;
    const octet CMD_PROTECTIVE_STOP = 1;
    const octet CMD_DEFAULT = 253;
    const octet CMD_IDLE = 254;

    const octet servoON = 0x01;
    const octet emergencyStop = 0x02;
    const octet protectiveStopLower = 0x04;
    const octet protectiveStopUpper = 0x08;

    /**
     * @brief
     */
    struct TimedJointData
    {
        /**
         * @brief Data Send Time
         */
        Time tm;

        /**
         * @brief Command Accept Time
         */
        sequence<Time> cmd;

        /**
         * @brief Command Accept RTC ID
         */
        sequence<octet> id;

        /**
         * @brief command angles[rad] of each part
         */
        sequence< sequence<double> > qCommand;

        /**
         * @brief current angles[rad] of each part
         */
        sequence< sequence<double> > qState;

        /**
         * @brief current velocities[rad/s] of each part
         */
        sequence< sequence<double> > dqState;

        /**
         * @brief servo command for each part
         */
        sequence<octet> servoCommand;

        /**
         * @brief servo state for each part
         */
        sequence<octet> servoState;

        /**
         * @brief results of collision detection for each part
         */
        sequence<octet> collisionFlag;
    };
};
