
#include "BasicDataType.idl"

module IIS {
	struct TimedVelocity { 
  		RTC::Time tm;
 		sequence<long> id;
 		double vx;
 		double vy;
		double w;
		sequence<double> error;
 	};

	struct TimedPosition {
 		RTC::Time tm;
 		sequence<long> id;
 		double x;
 		double y;
 		double theta;
 		sequence<double> error; 
	};
}; // end of module IIS

