from sample import *
funcList = [
  "Robot Hardware Setup",
  calibrateJoint,
  " ",
  "OnOff",
  servoOn,
  servoOff,
  servoOnHands,
  servoOffHands,
  EngageProtectiveStop,
  DisengageProtectiveStop,
  " ",
  "Play Patterns:",
  goInitial,
  goOffPose,
  # ikTest,
  # ikTest_interrupt,
  # ikTest_spline,
  # testPattern,
  # badPattern,
  " ", 
  # "Grasper:",
  # rhandOpen,
  # rhandOpen20,
  # rhandClose,
  # lhandOpen,
  # lhandOpen20,
  # lhandClose,
  " ",
#  "Check Setup:",
#  getVersion,
  " ",
  "etc:",
  saveLog,
  setupLogger,
#  reboot,
#  shutdown
]
