#!/bin/sh

export PATH=$PATH:`rospack find openrtm`/bin
export PYTHONPATH=$PYTHONPATH:`rospack find openrtm`/src/openrtm

DOTFILE=/tmp/rtcgraph$$.dot
echo "write to $DOTFILE"
rtcryo  | rtstodot  > $DOTFILE
(while [ `cat $DOTFILE | wc -l` -lt 5 ]; do echo "wait for rtcgraph..."; sleep 1; done; rosrun xdot xdot.py $DOTFILE ) &
trap 'pkill -KILL xdot.py' 0 2 3 15

# update
while [ 1 ] ; do
    # echo "write to $DOTFILE"
    rtcryo  | rtstodot  > $DOTFILE
    sleep 5
done



