#!/bin/sh

export PATH=$PATH:`rospack find openrtm`/bin
export PYTHONPATH=$PYTHONPATH:`rospack find openrtm`/src/openrtm
rtcryo  | rtstodot  | dot -Tpdf -o /tmp/rtcgraph$$.pdf && evince /tmp/rtcgraph$$.pdf

